/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef FPGE_PRIVATE_H
#define FPGE_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"0.6.1.3404"
#define VER_MAJOR	0
#define VER_MINOR	6
#define VER_RELEASE	1
#define VER_BUILD	3404
#define COMPANY_NAME	""
#define FILE_VERSION	""
#define FILE_DESCRIPTION	"Fred's Panzer General Editor"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"FPGE"
#define PRODUCT_VERSION	""

#endif /*FPGE_PRIVATE_H*/
